library(data.table)
house<-fread("household_power_consumption.txt")
power<-as.data.frame(house)
feb<-power[66637:69516,]
png(file="Plot4.png")
par(mfrow = c(2,2))
with(feb, {
  gap<-as.numeric(feb$Global_active_power)
  ts<-ts(gap,start=1,end=2,frequency=2880)
  plot(ts,ann=F,xaxt="n")
  axis(1, 1,labels="Thu");axis(1, 1.5,labels="Fri");axis(1, 2,labels="Sat")
  title(ylab="Global Active Power")
  
  volt<-as.numeric(feb$Voltage)
  ts<-ts(volt,start=1,end=2,frequency=2880)
  plot(ts,ann=F,xaxt="n")
  axis(1, 1,labels="Thu");axis(1, 1.5,labels="Fri");axis(1, 2,labels="Sat")
  title(xlab="datetime", ylab="Voltage")

  meter1<-as.matrix(feb[7]);meter2<-as.matrix(feb[8]);meter3<-as.matrix(feb[9])
  ts<-ts(meter1,start=1,end=2,frequency=2880)
  plot(ts, xaxt="n",ylab="Energy sub metering",xlab=NA)
  ts<-ts(meter2,start=1,end=2,frequency=2880)
  lines(ts,col="red")
  ts<-ts(meter3,start=1,end=2,frequency=2880)
  lines(ts,col="blue")
  axis(1, 1,labels="Thu");axis(1, 1.5,labels="Fri");axis(1, 2,labels="Sat")
  legend("topright", colnames(feb[7:9]),cex=0.9,lty="solid",bty="n",col=c("black","red","blue"))

  grea<-as.numeric(feb$Global_reactive_power)
  ts<-ts(grea,start=1,end=2,frequency=2880)
  plot(ts,ann=F,xaxt="n")
  axis(1, 1,labels="Thu");axis(1, 1.5,labels="Fri");axis(1, 2,labels="Sat")
  title(xlab="datetime", ylab="Global_reactive_power")
  })
dev.off()