library(data.table)
house<-fread("household_power_consumption.txt")
power<-as.data.frame(house)
feb<-power[66637:69516,]
meter1<-as.matrix(feb[7]);meter2<-as.matrix(feb[8]);meter3<-as.matrix(feb[9])
ts<-ts(meter1,start=1,end=2,frequency=2880)
png(file="Plot3.png")
plot(ts, xaxt="n",ylab="Energy sub metering",xlab=NA)
ts<-ts(meter2,start=1,end=2,frequency=2880)
lines(ts,col="red")
ts<-ts(meter3,start=1,end=2,frequency=2880)
lines(ts,col="blue")
axis(1, 1,labels="Thu");axis(1, 1.5,labels="Fri");axis(1, 2,labels="Sat")
legend("topright", colnames(feb[7:9]), lty="solid",col=c("black","red","blue"))
dev.off()